// ─── Core witness types ───────────────────────────────────────────────────────

export interface WitnessAssertion {
  /** Human-readable label shown in gate output when this assertion fails. */
  name: string;
  ok: boolean;
  detail?: string;
}

/**
 * The field continuity contract for one domain.
 *
 * Generated by `rivergen gen` as `apps/web/src/witness/<domain>.witness.ts`.
 * Developer fills the TODOs; Gate #12 enforces that all four layers pass.
 */
export interface DomainWitness<
  TPayload extends object = Record<string, unknown>,
> {
  /** Canonical domain key — matches the generator spec. */
  domain: string;

  /** All events this domain broadcasts. Must match the broadcast helper. */
  events: string[];

  /**
   * Minimal field set each projection reads from the payload.
   * Key: event name. Value: field names that must survive all hops.
   * Layer 1 + Layer 2 validate against this map.
   */
  requiredFields: Partial<Record<string, (keyof TPayload)[]>>;

  /**
   * Deterministic test payloads — one per event.
   * Must be supersets of requiredFields[event].
   * Use fixed IDs and timestamps — no randomUUID() or new Date() here.
   */
  testPayloads: Partial<
    Record<
      string,
      TPayload & {
        _meta: {
          resourceId: string;
          actor: { id: string; type: string };
          context: Record<string, string>;
          correlationId: string;
          eventVersion: string;
        };
      }
    >
  >;

  /**
   * Create → update → delete assertion sequence.
   * Called by the Layer 3 runner with a real QueryClient (cast from unknown).
   * MUST assert that every requiredField is present in the cache after each hop.
   */
  lifecycle: (queryClient: unknown) => Promise<WitnessAssertion[]>;

  /**
   * Custom event assertions (e.g. pinned, moved, archived).
   * Key: event name. Value: assertion function.
   * Called once per event by the Layer 3 runner.
   */
  signals: Record<string, (queryClient: unknown) => Promise<WitnessAssertion[]>>;
}

// ─── Runner output types ──────────────────────────────────────────────────────

export interface LayerResult {
  ok: boolean;
  violations: string[];
}

export interface DomainWitnessReport {
  domain: string;
  layer1: LayerResult; // schema contract (static)
  layer2: LayerResult; // broadcast contract (static)
  layer3: LayerResult; // projection proof (dynamic)
  layer4: LayerResult; // coverage completeness (static)
}

export interface WitnessResult {
  ok: boolean;
  domains: DomainWitnessReport[];
  totalDomains: number;
  passedDomains: number;
}
